name: Update Spiele

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install playwright
      - run: playwright install chromium

      - run: python assets/python/scraper.py

      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add assets/data/spiele.json
          git commit -m "Update Spiele" || echo "No changes"
          git push
